### ISSUE TITLE
Private link AI studio test failure

### ISSUE THREAD

**Issue by vyta** [Azure/terraform-azurerm-avm-res-machinelearningservices-workspace#33]
privatelink ai studio tests fails -- this should succeed if working properly

**Comment by cmaclaughlin** [comment]
`terraform destroy` deletes the private endpoint for the KV instance _before_ the instance. This is the test is failing on the destroy step and throwing the "Connection is not an approved private link and caller was ignored because bypass is not set to 'AzureServices' and PublicNetworkAccess is set to 'Disabled'." exception.
